### PR TITLE
fix imports

### PR DESCRIPTION
**Pull request by tomerlevi444**
Without this fix, the build fails.

### CODE REVIEW

**Comment by jadsonlourenco** [comment]
Thanks for the PR, but are you using RN = > 0.40?

**Comment by tomerlevi444** [comment]
I use RN 0.38
Is it not compatible with this version?

**Comment by jadsonlourenco** [comment]
@tomerlevi444 before v3.0 is, look: https://github.com/jadsonlourenco/react-native-shake-event/releases

**Comment by tomerlevi444** [comment]
Thanks

**Pull request closed without merging**
